{% set name = "heart-library" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/heart_library-{{ version }}.tar.gz
  sha256: 1d91b13beaa4c89a2d07f45d2860d472f32dcc11ea3263fdb26197eb76c6c1fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.12
    - adversarial-robustness-toolbox >=1.19.1
    - datasets >=3.2.0
    - maite >=0.7.0
    - multiprocess >=0.70.0
    - numpy >=1.18.5,<2
    - pillow >=11.0.0
    - scikit-learn >=0.22.2
    - six >=1.0.0
    - setuptools >=75
    - tqdm >=4.0.0
    - transformers >=4.0.0,<4.49.0

test:
  imports:
    - heart_library
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/heart-library
  summary: Hardened Extension of the Adversarial Robustness Toolbox (HEART) supports assessment of adversarial AI vulnerabilities in Test & Evaluation workflows.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jxn11
    - kieranfraser
    - lockwoodar
