{% set name = "heart-library" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heart_library-{{ version }}.tar.gz
  sha256: 174465700fdc97cd39f8d435542b61c74c3fedabd1d61669eeaead4ab0a8f83a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.12
    - adversarial-robustness-toolbox >=1.17.1
    - maite >=0.5.0
    - numpy >=1.18.5,<2
    - scikit-learn >=0.22.2
    - six
    - setuptools
    - tqdm

test:
  imports:
    - heart_library
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/heart-library
  summary: Hardened Extension of the Adversarial Robustness Toolbox (HEART) supports assessment of adversarial AI vulnerabilities in Test & Evaluation workflows.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jxn11
    - kieranfraser
    - lockwoodar
